#Hugo configuration
title = "qwesdcdfdw"
baseURL = "https:\/\/erwde.asd.wer"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
galleryChannelIds = ""

[params]
loginId = "1758823"
subfolder = ""
firstpartycookies = true
cookiedomain = "asd.wer"
